"""Generate grouping-eval fixtures from a compact scenario spec.

Each grouping scenario lives in its own eval directory
(`tests/llm/fixtures/test_ask_holmes/<id>/`) and is described by a single
`scenario.json`. This script renders the three files the eval harness consumes:

  - test_case.yaml   (user_prompt = the vendored triage prompt over the alerts,
                      plus expected_output / tags / include_tool_calls)
  - toolsets.yaml    (enables the two local mock MCP servers, seeded from seed.json,
                      and disables the default k8s/bash/etc. toolsets)
  - seed.json        (leaders + pending queue + recorded RCA evidence for the mocks)

Keeping the prompt generated (rather than hand-pasted) means every scenario uses
the identical, current triage prompt and can be re-rendered in one command if the
prompt is updated.

Usage (from the holmesgpt repo root):
    poetry run python tests/llm/fixtures/test_ask_holmes/shared/grouping/build_scenarios.py
    # or target specific dirs:
    poetry run python .../build_scenarios.py 283_grouping_undergroup_shared_trace

scenario.json shape:
    {
      "description": "...",
      "tags": ["medium", "mcp", "chain-of-causation"],
      "alerts":   [ {alert dict}, ... ],   # inlined into the prompt
      "leaders":  [ {incident}, ... ],     # optional pre-existing open incidents
      "pending":  [ {alert}, ... ],        # optional look-ahead queue
      "evidence": { "logs": {...}, "describe": {...}, "events": {...} },
      "expected_output": [ "...", ... ]
    }
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from triage_prompt import render_triage_prompt  # noqa: E402

FIXTURES_DIR = Path(__file__).resolve().parents[2]  # tests/llm/fixtures/test_ask_holmes
SHARED_REL = "tests/llm/fixtures/test_ask_holmes/shared/grouping"


def _indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line else line for line in text.splitlines())


def _render_test_case(scenario: dict) -> str:
    prompt = render_triage_prompt(scenario["alerts"], scenario.get("leaders"))
    lines = ["# GENERATED by build_scenarios.py from scenario.json — do not edit by hand."]
    if scenario.get("description"):
        lines.append(f"# {scenario['description']}")
    lines.append("")
    lines.append("user_prompt: |")
    lines.append(_indent(prompt, 2))
    lines.append("")
    lines.append("expected_output:")
    for item in scenario["expected_output"]:
        lines.append(f"  - {json.dumps(item, ensure_ascii=False)}")
    lines.append("")
    lines.append("include_tool_calls: true")
    lines.append("")
    lines.append("tags:")
    for tag in scenario.get("tags", []):
        lines.append(f"  - {tag}")
    lines.append("")
    return "\n".join(lines)


def _render_toolsets(scenario_dir_name: str) -> str:
    seed_rel = f"tests/llm/fixtures/test_ask_holmes/{scenario_dir_name}/seed.json"
    disabled = [
        "kubernetes/core",
        "kubernetes/logs",
        "helm/core",
        "bash",
        "internet",
        "robusta",
        "connectivity_check",
    ]
    lines = [
        "# GENERATED by build_scenarios.py — do not edit by hand.",
        "# Two local stdio MCP mocks give a fully self-contained grouping eval:",
        "#   incident_bridge  -> grouping tools (create/attach/list/search) in-memory",
        "#   rca_evidence     -> recorded per-resource logs/describe/events (the RCA 'model')",
        "# No Kubernetes, no Supabase, no external services.",
        "toolsets:",
        "  incident_bridge:",
        "    type: mcp",
        "    enabled: true",
        "    config:",
        "      mode: stdio",
        '      command: "python"',
        f'      args: ["{SHARED_REL}/mock_incident_bridge.py", "{seed_rel}"]',
        "  rca_evidence:",
        "    type: mcp",
        "    enabled: true",
        "    config:",
        "      mode: stdio",
        '      command: "python"',
        f'      args: ["{SHARED_REL}/mock_rca_evidence.py", "{seed_rel}"]',
    ]
    for name in disabled:
        lines.append(f"  {name}:")
        lines.append("    enabled: false")
    lines.append("")
    return "\n".join(lines)


def _render_seed(scenario: dict) -> str:
    seed = {
        "leaders": scenario.get("leaders", []),
        "pending": scenario.get("pending", []),
        "evidence": scenario.get("evidence", {}),
    }
    return json.dumps(seed, indent=2, ensure_ascii=False) + "\n"


def build_one(scenario_dir: Path) -> None:
    scenario = json.loads((scenario_dir / "scenario.json").read_text())
    (scenario_dir / "test_case.yaml").write_text(_render_test_case(scenario))
    (scenario_dir / "toolsets.yaml").write_text(_render_toolsets(scenario_dir.name))
    (scenario_dir / "seed.json").write_text(_render_seed(scenario))
    print(f"built {scenario_dir.name}")


def main(argv: list[str]) -> None:
    if argv:
        targets = [FIXTURES_DIR / name for name in argv]
    else:
        targets = [p.parent for p in FIXTURES_DIR.glob("*/scenario.json")]
    if not targets:
        print("no scenarios found")
        return
    for t in targets:
        build_one(t)


if __name__ == "__main__":
    main(sys.argv[1:])
