"""End-to-end evidence that MCP healthcheck improvements work.

Starts a real delayed MCP SSE server, points a real RemoteMCPToolset at it,
and runs the actual retry loop.  Records every real connection attempt with
timestamps and writes evidence to tests/evidence/mcp_healthcheck_backoff.md.

Run:
    poetry run pytest tests/test_mcp_healthcheck_evidence.py -s --no-cov
"""

import os
import signal
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Tuple

import pytest

import holmes.common.env_vars as env_vars
from holmes.plugins.toolsets.mcp.toolset_mcp import RemoteMCPToolset
from server import _get_next_refresh_interval

EVIDENCE_DIR = Path(__file__).parent / "evidence"
SERVER_SCRIPT = Path(__file__).parent / "delayed_mcp_server.py"
PORT = 9199

# Shortened schedule so the test finishes in ~30s instead of minutes.
# Same structure as production [30, 60, 120] — just compressed.
TEST_BACKOFF_SCHEDULE = [3, 5, 8]


def _ts() -> str:
    return datetime.now(timezone.utc).strftime("%H:%M:%S.%f")[:-3]


def _start_delayed_server(delay: int) -> subprocess.Popen:
    """Start the delayed MCP server as a real subprocess."""
    proc = subprocess.Popen(
        [sys.executable, str(SERVER_SCRIPT), "--port", str(PORT), "--delay", str(delay)],
        stderr=subprocess.PIPE,
        stdout=subprocess.PIPE,
    )
    # Give the OS a moment to bind or fail
    time.sleep(0.3)
    assert proc.poll() is None, f"Server process died immediately: {proc.stderr.read().decode()}"
    return proc


def _stop_server(proc: subprocess.Popen):
    proc.send_signal(signal.SIGTERM)
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait(timeout=3)


def _attempt_healthcheck(url: str) -> Tuple[bool, str]:
    """Create a real RemoteMCPToolset and attempt a real connection."""
    toolset = RemoteMCPToolset(
        name="delayed-test-server",
        description="e2e evidence test",
        config={"url": url},
    )
    return toolset.prerequisites_callable(config=toolset.config)


def _run_retry_loop(
    url: str,
    backoff_schedule: list,
    default_interval: int,
    max_cycles: int,
) -> List[dict]:
    """Simulate the server.py refresh loop with real connection attempts."""
    events = []
    backoff_index = 0

    for cycle in range(1, max_cycles + 1):
        ok, msg = _attempt_healthcheck(url)
        event = {
            "cycle": cycle,
            "time": _ts(),
            "ok": ok,
            "msg": msg,
            "backoff_index": backoff_index,
        }

        if ok:
            event["action"] = "RECOVERED"
            events.append(event)
            break

        # Determine next sleep using the real production function,
        # but with our shortened schedule patched in.
        sleep_time, backoff_index = _get_next_refresh_interval(
            has_failed_mcp=True,
            backoff_index=backoff_index,
            default_interval=default_interval,
        )
        event["action"] = "RETRY"
        event["next_sleep"] = sleep_time
        events.append(event)

        time.sleep(sleep_time)

    return events


PRODUCTION_BACKOFF_SCHEDULE = [30, 60, 120]


def _render_evidence(events: List[dict], delay: int, schedule: list) -> str:
    """Render a markdown evidence file from the recorded events."""
    lines = [
        "## MCP Healthcheck Improvements — End-to-End Evidence",
        "",
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        "",
        "This file is auto-generated by `tests/test_mcp_healthcheck_evidence.py`.",
        "It starts a **real delayed MCP SSE server** and points a **real",
        "`RemoteMCPToolset`** at it — no mocking.",
        "",
        "### Setup",
        "",
        f"- Delayed MCP server on `localhost:{PORT}` with **{delay}s startup delay**",
        f"- Backoff schedule (test-shortened): `{schedule}` seconds",
        f"- Production schedule: `{PRODUCTION_BACKOFF_SCHEDULE}` seconds",
        "",
        "### Timeline",
        "",
        "| Cycle | Time (UTC) | Result | Error / Status | Next sleep |",
        "|-------|------------|--------|----------------|------------|",
    ]

    for ev in events:
        if ev["action"] == "RECOVERED":
            lines.append(
                f"| {ev['cycle']} | `{ev['time']}` | **RECOVERED** | "
                f"Server up, tools loaded | — |"
            )
        else:
            # Truncate error message to keep table readable
            msg = ev["msg"]
            if len(msg) > 80:
                msg = msg[:77] + "..."
            lines.append(
                f"| {ev['cycle']} | `{ev['time']}` | FAILED | "
                f"`{msg}` | {ev['next_sleep']}s |"
            )

    lines.append("")

    # Verify error messages are clear
    failed_events = [e for e in events if e["action"] != "RECOVERED"]
    if failed_events:
        first_err = failed_events[0]["msg"]
        lines.extend([
            "### Error message clarity",
            "",
            "First failure message (full):",
            "",
            f"```",
            f"{first_err}",
            f"```",
            "",
        ])
        if "unhandled errors in a TaskGroup" in first_err:
            lines.append("**FAIL**: ExceptionGroup was NOT unwrapped.")
        else:
            lines.append(
                "**PASS**: The opaque `ExceptionGroup` wrapper has been unwrapped — "
                "users see the real error."
            )
        lines.append("")

    # Verify recovery
    recovered = [e for e in events if e["action"] == "RECOVERED"]
    lines.append("### Recovery")
    lines.append("")
    if recovered:
        lines.append(
            f"**PASS**: Server recovered on cycle {recovered[0]['cycle']} "
            f"at `{recovered[0]['time']}`."
        )
    else:
        lines.append("**FAIL**: Server did not recover within the retry window.")
    lines.append("")

    # Production comparison
    prod = PRODUCTION_BACKOFF_SCHEDULE
    lines.extend([
        "### Production backoff comparison",
        "",
        "| | 1st retry | 2nd retry | 3rd retry | Cumulative |",
        "|---|-----------|-----------|-----------|------------|",
        f"| Before (fixed 300s) | 300s | 300s | 300s | 900s |",
        f"| After (backoff) | {prod[0]}s | {prod[1]}s | {prod[2]}s | {sum(prod)}s |",
        "",
        f"If the MCP server is ready within ~2 min, recovery is"
        f" **{900 // sum(prod)}x faster**.",
        "",
    ])

    return "\n".join(lines) + "\n"


@pytest.mark.not_llm
class TestMCPHealthcheckEvidence:
    def test_end_to_end_backoff_and_recovery(self, monkeypatch):
        """Start a real delayed MCP server, retry with real toolset, record evidence."""
        delay = 12  # server comes up after 12 seconds
        default_interval = 30  # would be 300 in prod

        # Patch the schedule so the test is fast but uses the real function
        monkeypatch.setattr(env_vars, "MCP_RETRY_BACKOFF_SCHEDULE", TEST_BACKOFF_SCHEDULE)
        # Re-import so _get_next_refresh_interval sees the patched value
        import server
        monkeypatch.setattr(server, "MCP_RETRY_BACKOFF_SCHEDULE", TEST_BACKOFF_SCHEDULE)

        url = f"http://localhost:{PORT}"
        proc = _start_delayed_server(delay)
        try:
            events = _run_retry_loop(
                url=url,
                backoff_schedule=TEST_BACKOFF_SCHEDULE,
                default_interval=default_interval,
                max_cycles=10,
            )
        finally:
            _stop_server(proc)

        # Assertions
        failed_events = [e for e in events if e["action"] != "RECOVERED"]
        recovered_events = [e for e in events if e["action"] == "RECOVERED"]

        # Must have failed at least once (server delayed 12s, first retry at 3s)
        assert len(failed_events) >= 1, "Expected at least one failure before recovery"

        # Must have recovered
        assert len(recovered_events) == 1, f"Expected recovery, got events: {events}"

        # Error messages must NOT contain the opaque ExceptionGroup wrapper
        for ev in failed_events:
            assert "unhandled errors in a TaskGroup" not in ev["msg"], (
                f"ExceptionGroup not unwrapped: {ev['msg']}"
            )
            assert "retry automatically" in ev["msg"], (
                f"Missing retry hint: {ev['msg']}"
            )

        # Write evidence
        md = _render_evidence(events, delay, TEST_BACKOFF_SCHEDULE)
        EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
        evidence_path = EVIDENCE_DIR / "mcp_healthcheck_backoff.md"
        evidence_path.write_text(md)

        print(f"\n{'=' * 70}")
        print(md)
        print(f"{'=' * 70}")
        print(f"Evidence written to {evidence_path}")
