nav:
    - Overview & Installation: index.md
    - Health Checks: health-checks.md
    - Scheduled Health Checks: scheduled-health-checks.md
    - Configuration: configuration.md
    - Troubleshooting: troubleshooting.md
    - Development Guide: development.md
