"""OpenTelemetry instrumentation for HolmesGPT (experimental).

This package lives under ``experimental/`` because the OTEL instrumentation API
is still evolving (span names, attribute keys, metric definitions). All integration
points in server.py and server-agui.py use try/except with no-op fallbacks, so this
package can be removed or relocated without breaking core HolmesGPT functionality.

Once the API stabilizes, this can move to a non-experimental location.
"""

from experimental.otel.attributes import (  # Correlation IDs; Gen AI Required Attributes; LLM Request/Response; Token Usage; Tool/Function Calling; Agent-Specific; Result Attributes; Cost Tracking; Span Names; Granular Span Names; Context Attributes; Metric Names; Token Type; Truncation
    AGENT_ITERATION,
    AGENT_NAME,
    AGENT_TYPE,
    ANSWER_LENGTH,
    CONTEXT_TOKENS_LIMIT,
    CONTEXT_TOKENS_USED,
    CONVERSATION_ID,
    COST_USD,
    ERROR_MESSAGE,
    ERROR_TYPE,
    FINISH_REASON,
    INPUT_TOKENS,
    MAX_ATTRIBUTE_SIZE,
    MAX_TOKENS,
    MESSAGES_IN_CONTEXT,
    METRIC_AGENT_ERRORS,
    METRIC_AGENT_ITERATIONS,
    METRIC_AGENT_TOOL_CALLS,
    METRIC_OPERATION_DURATION,
    METRIC_TOKEN_USAGE,
    METRIC_TOOL_DURATION,
    MODEL,
    OPERATION_NAME,
    OUTPUT_TOKENS,
    PROVIDER_NAME,
    REQUEST_ID,
    RESPONSE_MODEL,
    RESULT_OUTPUT,
    RESULT_SUCCESS,
    SPAN_AGENT_RUN,
    SPAN_BUILD_CONVERSATION_HISTORY,
    SPAN_BUILD_SYSTEM_PROMPT,
    SPAN_CHAT,
    SPAN_CHECK_CONTEXT_LIMITS,
    SPAN_COMPACT_HISTORY,
    SPAN_CONTEXT_LIMIT_EXCEEDED,
    SPAN_EXECUTE_TOOL,
    SPAN_FALLBACK_STRUCTURED_OUTPUT,
    SPAN_GENERATE_ANSWER,
    SPAN_HANDLE_LLM_ERROR,
    SPAN_HANDLE_TOOL_ERROR,
    SPAN_INVOKE_AGENT,
    SPAN_INVOKE_TOOL,
    SPAN_LLM_COMPLETION,
    SPAN_LLM_INFERENCE,
    SPAN_PARSE_ARGUMENTS,
    SPAN_PARSE_RESPONSE,
    SPAN_PREPARE_MESSAGES,
    SPAN_PROCESS_RESULT,
    SPAN_RETRY_ATTEMPT,
    SPAN_TOOL_EXECUTE,
    SYSTEM,
    TEMPERATURE,
    TOKEN_TYPE,
    TOKEN_TYPE_INPUT,
    TOKEN_TYPE_OUTPUT,
    TOOL_CALL_COUNT,
    TOOL_CALL_ID,
    TOOL_DURATION_MS,
    TOOL_INPUT,
    TOOL_NAME,
    TOOL_OUTPUT,
    TOOL_STATUS,
    TOOLS_AVAILABLE,
    TOTAL_TOKENS,
    TRUNCATION_MARKER,
    USER_QUERY_LENGTH,
    truncate,
)
from experimental.otel.metrics import (
    get_meter,
    increment_errors,
    increment_iterations,
    increment_tool_calls,
    init_otel_metrics,
    record_operation_duration,
    record_token_usage,
    record_tool_duration,
    shutdown_otel_metrics,
)
from experimental.otel.otel_logging import (
    OTELContextFormatter,
    get_otel_logger,
    log_agent_complete,
    log_agent_error,
    log_agent_start,
    log_llm_call,
    log_tool_execution,
    setup_otel_logging,
)
from experimental.otel.tracing import (
    get_tracer,
    init_otel_tracer,
    needs_aws_auth,
    set_span_error,
    shutdown_otel_tracer,
)

__all__ = [
    # Tracing
    "init_otel_tracer",
    "get_tracer",
    "shutdown_otel_tracer",
    "set_span_error",
    "needs_aws_auth",
    # Metrics
    "init_otel_metrics",
    "get_meter",
    "shutdown_otel_metrics",
    "record_token_usage",
    "record_operation_duration",
    "record_tool_duration",
    "increment_iterations",
    "increment_tool_calls",
    "increment_errors",
    # Logging
    "OTELContextFormatter",
    "setup_otel_logging",
    "get_otel_logger",
    "log_llm_call",
    "log_tool_execution",
    "log_agent_start",
    "log_agent_complete",
    "log_agent_error",
    # Attributes - Correlation IDs
    "REQUEST_ID",
    "CONVERSATION_ID",
    # Attributes - Gen AI Required
    "OPERATION_NAME",
    "PROVIDER_NAME",
    # Attributes - LLM Request/Response
    "SYSTEM",
    "MODEL",
    "RESPONSE_MODEL",
    "TEMPERATURE",
    "MAX_TOKENS",
    "FINISH_REASON",
    # Attributes - Token Usage
    "INPUT_TOKENS",
    "OUTPUT_TOKENS",
    "TOTAL_TOKENS",
    # Attributes - Tool/Function Calling
    "TOOL_NAME",
    "TOOL_CALL_ID",
    "TOOL_INPUT",
    "TOOL_OUTPUT",
    "TOOL_DURATION_MS",
    "TOOL_STATUS",
    # Attributes - Agent-Specific
    "AGENT_NAME",
    "AGENT_TYPE",
    "AGENT_ITERATION",
    # Attributes - Result
    "RESULT_SUCCESS",
    "RESULT_OUTPUT",
    "ERROR_MESSAGE",
    "ERROR_TYPE",
    # Attributes - Cost
    "COST_USD",
    # Span Names
    "SPAN_AGENT_RUN",
    "SPAN_LLM_INFERENCE",
    "SPAN_TOOL_EXECUTE",
    "SPAN_INVOKE_AGENT",
    "SPAN_CHAT",
    "SPAN_EXECUTE_TOOL",
    # Granular Span Names
    "SPAN_PREPARE_MESSAGES",
    "SPAN_BUILD_SYSTEM_PROMPT",
    "SPAN_BUILD_CONVERSATION_HISTORY",
    "SPAN_LLM_COMPLETION",
    "SPAN_PARSE_RESPONSE",
    "SPAN_PARSE_ARGUMENTS",
    "SPAN_INVOKE_TOOL",
    "SPAN_PROCESS_RESULT",
    "SPAN_CHECK_CONTEXT_LIMITS",
    "SPAN_COMPACT_HISTORY",
    "SPAN_GENERATE_ANSWER",
    "SPAN_HANDLE_LLM_ERROR",
    "SPAN_HANDLE_TOOL_ERROR",
    "SPAN_RETRY_ATTEMPT",
    "SPAN_CONTEXT_LIMIT_EXCEEDED",
    "SPAN_FALLBACK_STRUCTURED_OUTPUT",
    # Context Attributes
    "MESSAGES_IN_CONTEXT",
    "TOOLS_AVAILABLE",
    "CONTEXT_TOKENS_USED",
    "CONTEXT_TOKENS_LIMIT",
    "USER_QUERY_LENGTH",
    "ANSWER_LENGTH",
    "TOOL_CALL_COUNT",
    # Metric Names
    "METRIC_TOKEN_USAGE",
    "METRIC_OPERATION_DURATION",
    "METRIC_TOOL_DURATION",
    "METRIC_AGENT_ITERATIONS",
    "METRIC_AGENT_TOOL_CALLS",
    "METRIC_AGENT_ERRORS",
    # Token Type
    "TOKEN_TYPE",
    "TOKEN_TYPE_INPUT",
    "TOKEN_TYPE_OUTPUT",
    # Utilities
    "truncate",
    "MAX_ATTRIBUTE_SIZE",
    "TRUNCATION_MARKER",
]
